#!/usr/bin/env bash

# Colors
COL_BLUE="\x1b[36;01m"
COL_BLUE="\x1b[32;01m"
COL_RESET="\x1b[39;49;00m"
COL_RED="\x1b[31;01m"

# Helper functions
_print() {
  printf $COL_BLUE"\n$1\n"$COL_RESET
}

_error() {
  _print $COL_RED"\n[Error] $1\n"
}

_success() {
  _print $COL_GREEN"\n$1\n"
}

_usage() {                 
  _print "  Usage:            install [-ah] 

  Options: 

  -h                Show this message 
  " 

  exit 0 
} 

#############################################################################

_install() {
  # Vundle
  _print "Installing Vundle"
  if [ -d "./bundle/vundle" ] ; then
    _print "Vundle is already installed"
  else
    git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
  fi

  curdir=$(pwd)

  # Backup vimrc if exists + symlink new vimrc
  if [ -f "$HOME/.vimrc" ] || [ -L "$HOME/.vimrc" ] ; then
    mv "$HOME/.vimrc" "$HOME/.vimrc.backup" 
  fi
  ln -s $curdir/vimrc ~/.vimrc

  # Backup gvimrc if exists + symlink new gvimrc
  if [ -f "$HOME/.gvimrc" ] || [ -L "$HOME/.gvimrc" ] ; then
    mv "$HOME/.gvimrc" "$HOME/.gvimrc.backup" 
  fi

  ln -s $curdir/gvimrc ~/.gvimrc

  _print "Spin Vim for a setup run"

  vim . -c 'BundleInstall' -c 'qa'

  _success "Ready to rock"
}

#############################################################################

if [ $# -eq 0 ]; then
  _print "Installing"
  _install
fi

#############################################################################

# parse arguments
while getopts :ha opt; do  
  case $opt in 
    h) 
    _usage 
    ;; 
    *) 
    _error "Invalid option received" 
    _usage 
    exit 0
    ;;
  esac 
done
